apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: notesapp
type: Opaque
data:
  mysql-root-password: cm9vdA==       # base64 for "root"
  mysql-database: dGVzdF9kYg==       # base64 for "test_db"

